# Generated by Django 5.1.6 on 2025-03-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeveloperDiary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("overview", models.TextField()),
                ("image_path", models.CharField(max_length=200)),
                ("full_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("real_name", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
                ("attack_type", models.CharField(max_length=100)),
                ("team", models.JSONField()),
                ("difficulty", models.IntegerField()),
                ("bio", models.TextField()),
                ("lore", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IsWin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("is_win", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_uid", models.CharField(max_length=255)),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                ("level", models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=20)),
                ("value", models.IntegerField()),
                ("icon", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ScoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("score_info", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Costume",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("quality_name", models.CharField(default="Unknown", max_length=100)),
                ("quality_color", models.CharField(default="gray", max_length=50)),
                ("quality_value", models.IntegerField(default=1)),
                ("quality_icon", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="No description available")),
                (
                    "appearance",
                    models.TextField(default="No appearance data available"),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costumes",
                        to="core.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("type", models.CharField(default="Normal", max_length=100)),
                ("is_collab", models.BooleanField(default=False)),
                ("key", models.CharField(default="", max_length=100)),
                ("damage", models.CharField(default="0", max_length=300)),
                ("casting", models.TextField(default="")),
                ("cooldown", models.CharField(default="0s", max_length=300)),
                ("projectile_speed", models.CharField(default="0m/s", max_length=150)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abilities",
                        to="core.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assists", models.IntegerField(default=0)),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                (
                    "is_win",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.iswin"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_map_id", models.IntegerField()),
                ("map_thumbnail", models.CharField(max_length=255)),
                ("match_play_duration", models.CharField(max_length=100)),
                ("match_season", models.FloatField()),
                ("match_uid", models.CharField(max_length=255)),
                ("match_winner_side", models.IntegerField()),
                ("mvp_uid", models.CharField(max_length=255)),
                ("svp_uid", models.CharField(max_length=255)),
                ("match_time_stamp", models.BigIntegerField()),
                ("play_mode_id", models.IntegerField()),
                ("game_mode_id", models.IntegerField()),
                ("camp", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "player_hero",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hero",
                    ),
                ),
                (
                    "match_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.matchplayer",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.player",
                    ),
                ),
                (
                    "score_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scoreinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transformation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("health", models.CharField(max_length=255)),
                ("movement_speed", models.CharField(max_length=50)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformations",
                        to="core.hero",
                    ),
                ),
            ],
        ),
    ]
