# Generated by Django 5.1.6 on 2025-03-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchhistory",
            name="match_uid",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
    ]
