# Generated by Django 5.1.6 on 2025-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchhistory",
            name="disconnected",
            field=models.BooleanField(default=False),
        ),
    ]
