# Generated by Django 5.1.6 on 2025-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_matchhistory_match_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchesplayer",
            name="camp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="cur_hero_icon",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="cur_hero_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="total_damage_taken",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="total_hero_damage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="total_hero_heal",
            field=models.FloatField(default=0.0),
        ),
    ]
