# Generated by Django 5.1.6 on 2025-03-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero_rename_content_tutorial_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='bio',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='lore',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='real_name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='role',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('ability_type', models.CharField(max_length=100)),
                ('is_collab', models.BooleanField(default=False)),
                ('additional_fields', models.JSONField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='core.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('appearance', models.TextField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to='core.hero')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('health', models.IntegerField()),
                ('movement_speed', models.CharField(max_length=50)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='core.hero')),
            ],
        ),
    ]
