# Generated by Django 5.1.6 on 2025-03-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_matchesplayer_camp_matchesplayer_cur_hero_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchesplayer",
            name="match",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.match",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="nick_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="player_icon",
            field=models.IntegerField(default=0),
        ),
    ]
