# Generated by Django 5.1.6 on 2025-03-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quality_hero_attack_type_hero_bio_hero_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='team',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
