# Generated by Django 5.1.6 on 2025-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hero_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='health',
            field=models.IntegerField(default=0),
        ),
    ]
