# Generated by Django 5.1.6 on 2025-03-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_matchesplayer_match_matchesplayer_nick_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchesplayer",
            name="camp",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="cur_hero_icon",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="cur_hero_id",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="match",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="nick_name",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="player_icon",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="total_damage_taken",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="total_hero_damage",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="total_hero_heal",
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="is_win",
            field=models.BooleanField(default=False),
        ),
    ]
