# Generated by Django 5.1.6 on 2025-03-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_scoreinfo_match_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchesPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assists", models.IntegerField(default=0)),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                (
                    "is_win",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.iswin"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matchhistory",
            name="match_player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.matchesplayer",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MatchPlayer",
        ),
    ]
