# Generated by Django 5.1.6 on 2025-03-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_matchesplayer_matchhistory_match_player_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchhistory",
            name="match_player",
        ),
        migrations.AddField(
            model_name="matchhistory",
            name="matches_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.matchesplayer",
            ),
        ),
    ]
