# Generated by Django 5.1.6 on 2025-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transformation_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='health',
            field=models.CharField(max_length=255),
        ),
    ]
