# Generated by Django 5.1.6 on 2025-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_matchhistory_match_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchesplayer",
            name="match_uid",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
