# Generated by Django 5.1.6 on 2025-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transformation_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='quality',
        ),
        migrations.AddField(
            model_name='costume',
            name='quality_color',
            field=models.CharField(default='gray', max_length=50),
        ),
        migrations.AddField(
            model_name='costume',
            name='quality_icon',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='costume',
            name='quality_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='costume',
            name='quality_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='costume',
            name='appearance',
            field=models.TextField(default='No appearance data available'),
        ),
        migrations.AlterField(
            model_name='costume',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
