# Generated by Django 5.1.6 on 2025-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_matchesplayer_match_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchesplayer",
            name="player_uid",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
