# Generated by Django 5.1.6 on 2025-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_costume_quality_costume_quality_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='ability_type',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='additional_fields',
        ),
        migrations.AddField(
            model_name='ability',
            name='casting',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(default='0s', max_length=50),
        ),
        migrations.AddField(
            model_name='ability',
            name='damage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='ability',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ability',
            name='projectile_speed',
            field=models.CharField(default='0m/s', max_length=50),
        ),
        migrations.AddField(
            model_name='ability',
            name='type',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
