# Generated by Django 5.1.6 on 2025-03-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_matchesplayer_player_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchesplayer",
            name="match_uid",
        ),
        migrations.RemoveField(
            model_name="matchesplayer",
            name="player_uid",
        ),
    ]
