# Generated by Django 5.1.6 on 2025-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ability_ability_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(default='0s', max_length=150),
        ),
        migrations.AlterField(
            model_name='ability',
            name='damage',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='ability',
            name='projectile_speed',
            field=models.CharField(default='0m/s', max_length=150),
        ),
    ]
