# Generated by Django 5.1.6 on 2025-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ability_cooldown_alter_ability_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(default='0s', max_length=300),
        ),
    ]
