# Generated by Django 5.1.6 on 2025-03-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_matchesplayer_match_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_id", models.IntegerField(unique=True)),
                ("hero_name", models.CharField(max_length=100)),
                ("hero_type", models.URLField()),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("play_time", models.FloatField()),
                ("total_hero_damage", models.FloatField()),
                ("total_damage_taken", models.FloatField()),
                ("total_hero_heal", models.FloatField(default=0)),
                ("len_heroes", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="matchesplayer",
            name="player_hero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playerhero",
            ),
            preserve_default=False,
        ),
    ]
