# Generated by Django 5.1.6 on 2025-03-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_playerhero_matchesplayer_player_hero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerhero",
            name="len_heroes",
        ),
        migrations.AlterField(
            model_name="matchesplayer",
            name="player_hero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playerhero",
            ),
        ),
    ]
