# Generated by Django 5.1.6 on 2025-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ability_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='damage',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
