# Generated by Django 5.1.6 on 2025-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_developerdiary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerdiary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
