# Generated by Django 5.1.6 on 2025-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_developerdiary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerdiary",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
