# Generated by Django 5.1.6 on 2025-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_developerdiary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerdiary",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
