# Generated by Django 5.1.6 on 2025-03-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_developerdiary_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("score_info", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_uid", models.CharField(max_length=255)),
                ("assists", models.IntegerField()),
                ("kills", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("is_win", models.BooleanField()),
                ("disconnected", models.BooleanField()),
                ("camp", models.CharField(max_length=1)),
                (
                    "player_hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hero"
                    ),
                ),
                (
                    "score_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scoreinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_map_id", models.IntegerField()),
                ("map_thumbnail", models.CharField(max_length=255)),
                ("match_play_duration", models.CharField(max_length=100)),
                ("match_season", models.FloatField()),
                ("match_uid", models.CharField(max_length=255)),
                ("match_winner_side", models.CharField(max_length=1)),
                ("mvp_uid", models.CharField(max_length=255)),
                ("svp_uid", models.CharField(max_length=255)),
                ("match_time_stamp", models.BigIntegerField()),
                ("play_mode_id", models.IntegerField()),
                ("game_mode_id", models.IntegerField()),
                (
                    "match_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "score_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scoreinfo"
                    ),
                ),
            ],
        ),
    ]
