# Generated by Django 5.1.6 on 2025-03-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_playerstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMatches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
